#!/bin/bash

set -e -u

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git clone ./concourse-bosh-deployment ./bumped-repo

concourse_version="$(cat concourse-boshio/version)"

cat ./concourse-bosh-deployment/versions.yml | \
  sed -e "s/concourse_version: .*/concourse_version: '$concourse_version'/" | \
  sed -e "s/concourse_sha1: .*/concourse_sha1: '$(cat concourse-boshio/sha1)'/" | \
  sed -e "s/bpm_version: .*/bpm_version: '$(cat bpm-release/version)'/" | \
  sed -e "s/bpm_sha1: .*/bpm_sha1: '$(cat bpm-release/sha1)'/" | \
  sed -e "s/postgres_version: .*/postgres_version: '$(cat postgres-release/version)'/" | \
  sed -e "s/postgres_sha1: .*/postgres_sha1: '$(cat postgres-release/sha1)'/" \
  > bumped-repo/versions.yml

cd bumped-repo

git add -A
git commit -m "bump versions.yml" --allow-empty
git tag -f "v$concourse_version"
