---
name: ((deployment_name))

releases:
- name: concourse
  version: ((concourse_version))
  sha1: ((concourse_sha1))
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=((concourse_version))
- name: bpm
  version: ((bpm_version))
  sha1: ((bpm_sha1))
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=((bpm_version))
- name: postgres
  version: ((postgres_version))
  sha1: ((postgres_sha1))
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=((postgres_version))

instance_groups:
- name: db
  instances: 1
  azs: ((azs))
  networks: [{name: ((network_name))}]
  stemcell: jammy
  vm_type: ((db_vm_type))
  persistent_disk_type: ((db_persistent_disk_type))
  jobs:
  - release: postgres
    name: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: &db_name atc
        roles:
        - &db_role
          name: concourse
          password: ((postgres_password))

- name: web
  instances: 1
  azs: ((azs))
  networks: [{name: ((network_name))}]
  stemcell: jammy
  vm_type: ((web_vm_type))
  jobs:
  - release: bpm
    name: bpm

  - release: concourse
    name: web
    properties:
      token_signing_key: ((token_signing_key))

      external_url: ((external_url))

      postgresql:
        database: *db_name
        role: *db_role

      worker_gateway:
        host_key: ((tsa_host_key))
        authorized_keys: |
          ((worker_key.public_key))

- name: worker
  instances: 1
  azs: ((azs))
  networks: [{name: ((network_name))}]
  stemcell: jammy
  vm_type: ((worker_vm_type))
  jobs:
  - release: concourse
    name: worker
    properties:
      drain_timeout: 10m
      worker_gateway: {worker_key: ((worker_key))}

variables:
- name: postgres_password
  type: password
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh

stemcells:
- alias: jammy
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000