name: ((deployment_name))

releases:
- name: concourse
  version: ((concourse_version))
  sha1: ((concourse_sha1))
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=((concourse_version))

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: worker
  instances: ((instances))
  azs: ((azs))
  vm_type: ((worker_vm_type))
  stemcell: xenial
  networks: [{name: ((external_worker_network_name))}]
  jobs:
  - name: worker
    release: concourse
    properties:
      log_level: debug
      tags: ((worker_tags))
      worker_gateway:
        hosts: ["((tsa_host)):2222"]
        host_public_key: ((tsa_host_key.public_key))
        worker_key: ((worker_key))

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
